<a href="https://colab.research.google.com/github/apcyssr/2026_Spring_KBU/blob/main/0320_03_REST_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **[The birth-web](https://home.cern/science/computing/birth-web)**

<img src='https://urbandesignlab.in/wp-content/uploads/2022/06/1-6.jpg' width=600>

# REST API란?

- REST API는 웹 서비스를 설계하고 사용하는 방식 중 하나로, REST(Representational State Transfer) 아키텍처 스타일에 기반한 API(Application Programming Interface)를 의미합니다.
- REST API는 웹 상에서 다른 시스템 간에 데이터를 주고받기 위한 표준화된 방법을 제공하여, 서로 다른 시스템 간의 상호작용을 간단하고 효율적으로 만들어 줍니다. REST API의 주요 개념을 설명하면 다음과 같습니다:

## 1. REST의 개념
- REST는 자원을 "표현(representation)"하고 상태를 "전송(transfer)"하는 아키텍처 스타일로서, 웹의 기본 프로토콜인 HTTP를 사용해 데이터를 전달합니다.
- RESTful 시스템은 클라이언트와 서버 간에 데이터를 주고받기 위한 규칙을 따르며, 클라이언트는 특정 자원을 요청하고 서버는 그에 대한 응답을 반환합니다.

<img src='https://media.geeksforgeeks.org/wp-content/uploads/20230216170349/What-is-an-API.png' height=500>


## 2. REST API의 구성 요소
REST API는 다음과 같은 주요 구성 요소로 이루어져 있습니다.

- **자원(Resource)**:  
  REST에서 다루는 데이터의 모든 것을 자원이라고 부릅니다. 자원은 URL(예: `/products/123`)로 고유하게 식별됩니다.

- **HTTP 메소드**:  
  REST API는 자원에 대해 특정한 작업을 수행하기 위해 HTTP 메소드를 사용합니다.
  - **GET**: 자원을 조회합니다.
  - **POST**: 자원을 생성합니다.
  - **PUT**: 자원을 전체적으로 업데이트합니다.
  - **PATCH**: 자원을 부분적으로 업데이트합니다.
  - **DELETE**: 자원을 삭제합니다.

- **엔드포인트(Endpoint)**:  
  자원에 접근할 수 있는 URL입니다. 예를 들어, `https://example.com/api/products`는 상품 자원에 대한 엔드포인트입니다.

- **HTTP 상태 코드**:  
  요청의 성공, 실패 등 결과를 알려주는 숫자 코드입니다.
  - **200 OK**: 요청이 성공적으로 처리되었음을 의미합니다.
  - **201 Created**: 새로운 자원이 성공적으로 생성되었음을 의미합니다.
  - **400 Bad Request**: 잘못된 요청이 발생했음을 의미합니다.
  - **404 Not Found**: 요청한 자원을 찾을 수 없음을 의미합니다.
  - **500 Internal Server Error**: 서버에서 예기치 않은 오류가 발생했음을 의미합니다.

<img src='https://miro.medium.com/v2/resize:fit:1100/format:webp/1*OcmVkcsM5BWRHrg8GC17iw.png' width = 700 height=200>

### <font color='orange'>**An API is not a database. It is an access point to an app that can access a database.**


## 3. REST API의 특징
- **무상태(Stateless)**:  
  각 요청은 독립적이며, 서버는 클라이언트의 이전 요청에 대한 상태를 저장하지 않습니다. 따라서 모든 요청은 필요한 정보를 자체적으로 포함해야 합니다.

- **클라이언트-서버 구조**:  
  RESTful 서비스는 클라이언트와 서버의 역할을 분리합니다. 클라이언트는 데이터를 요청하고, 서버는 요청을 처리하여 데이터를 반환합니다.

- **캐시 가능(Cacheable)**:  
  서버 응답이 캐시될 수 있어야 합니다. 캐싱을 통해 클라이언트의 요청에 대한 응답 속도를 높이고 서버의 부하를 줄일 수 있습니다.

## 4. REST API의 장점
- **간단한 구조**: REST는 HTTP 기반으로 동작하므로 HTTP 표준 메소드와 상태 코드를 사용하여 직관적으로 이해할 수 있습니다.
- **유연성**: 다양한 클라이언트(웹 브라우저, 모바일 앱 등)에서 쉽게 사용할 수 있습니다.
- **범용성**: RESTful API는 표준 HTTP 프로토콜을 사용하므로 대부분의 네트워크 환경에서 사용이 가능합니다.

## 5. 예시
예를 들어, 전자상거래 시스템에서 제품 정보를 조회하는 REST API 엔드포인트가 있다고 가정해 보겠습니다.

- **GET 요청으로 제품 목록 조회**: `GET /api/products`
- **GET 요청으로 특정 제품 조회**: `GET /api/products/123`
- **POST 요청으로 새로운 제품 생성**: `POST /api/products`
- **PUT 요청으로 기존 제품 정보 전체 수정**: `PUT /api/products/123`
- **DELETE 요청으로 특정 제품 삭제**: `DELETE /api/products/123`

이런 RESTful API를 통해, 클라이언트는 서버의 자원에 접근하거나 수정할 수 있습니다.

## 6. REST API와 JSON
- REST API는 주로 **JSON** 형식으로 데이터를 주고받습니다.
- JSON은 사람이 읽고 쓰기 쉬우며 컴퓨터도 효율적으로 처리할 수 있어 REST API에서 데이터 포맷으로 많이 사용됩니다.

## 요약
- REST API는 웹의 HTTP를 활용하여 서버와 클라이언트 간의 데이터를 주고받는 가장 보편적이고 간결한 방식입니다.
- REST는 상태를 유지하지 않으며, 특정 자원에 대해 URL을 통해 접근하고, 이를 조작하기 위해 HTTP 메소드를 사용합니다.
- 이를 통해 다양한 시스템 간의 원활한 통신을 가능하게 해줍니다.

<img src='https://images.ctfassets.net/vwq10xzbe6iz/5sBH4Agl614xM7exeLsTo7/9e84dce01735f155911e611c42c9793f/rest-api.png'>

### **[HTTP_방식 연습_click](https://httpbin.org/)**
### http://httpbin.org/get 웹서버로 실습
### https://curlconverter.com/ curltopython

In [ ]:
'''
{
  "args": {},
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
    "Host": "httpbin.org",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "X-Amzn-Trace-Id": "Root=1-64d6350b-4d8c7710021da0ab4ccabacc"
  },
  "origin": "112.169.221.81",
  "url": "http://httpbin.org/get"
}
'''

'\n{\n  "args": {},\n  "headers": {\n    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",\n    "Host": "httpbin.org",\n    "Upgrade-Insecure-Requests": "1",\n    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",\n    "X-Amzn-Trace-Id": "Root=1-64d6350b-4d8c7710021da0ab4ccabacc"\n  },\n  "origin": "112.169.221.81",\n  "url": "http://httpbin.org/get"\n}\n'

In [ ]:
import requests
r = requests.get('https://httpbin.org/')
print(r)

<Response [200]>

### windown 검색 창에 "cmd"를 입력하고 위의 코드를 curl 명령어로 변환하여 실행해보자

In [ ]:
# header & body
print(r.text)

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>httpbin.org</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700"
        rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/flasgger_static/swagger-ui.css">
    <link rel="icon" type="image/png" href="/static/favicon.ico" sizes="64x64 32x32 16x16" />
    <style>
        html {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }

        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }

        body {
            margin: 0;
            background: #fafafa;
        }
    </style>
</head>

<body>
    <a href="https://github.com/requests/httpbin" class="github-corner" aria-label="View source on Github">
        <svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;"
            aria-hidden="true">
            <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
            <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2"
                fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
            <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z"
                fill="currentColor" class="octo-body"></path>
        </svg>
    </a>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:absolute;width:0;height:0">
        <defs>
            <symbol viewBox="0 0 20 20" id="unlocked">
                <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V6h2v-.801C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8z"></path>
            </symbol>

            <symbol viewBox="0 0 20 20" id="locked">
                <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8zM12 8H8V5.199C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8z"
                />
            </symbol>

            <symbol viewBox="0 0 20 20" id="close">
                <path d="M14.348 14.849c-.469.469-1.229.469-1.697 0L10 11.819l-2.651 3.029c-.469.469-1.229.469-1.697 0-.469-.469-.469-1.229 0-1.697l2.758-3.15-2.759-3.152c-.469-.469-.469-1.228 0-1.697.469-.469 1.228-.469 1.697 0L10 8.183l2.651-3.031c.469-.469 1.228-.469 1.697 0 .469.469.469 1.229 0 1.697l-2.758 3.152 2.758 3.15c.469.469.469 1.229 0 1.698z"
                />
            </symbol>

            <symbol viewBox="0 0 20 20" id="large-arrow">
                <path d="M13.25 10L6.109 2.58c-.268-.27-.268-.707 0-.979.268-.27.701-.27.969 0l7.83 7.908c.268.271.268.709 0 .979l-7.83 7.908c-.268.271-.701.27-.969 0-.268-.269-.268-.707 0-.979L13.25 10z"
                />
            </symbol>

            <symbol viewBox="0 0 20 20" id="large-arrow-down">
                <path d="M17.418 6.109c.272-.268.709-.268.979 0s.271.701 0 .969l-7.908 7.83c-.27.268-.707.268-.979 0l-7.908-7.83c-.27-.268-.27-.701 0-.969.271-.268.709-.268.979 0L10 13.25l7.418-7.141z"
                />
            </symbol>


            <symbol viewBox="0 0 24 24" id="jump-to">
                <path d="M19 7v4H5.83l3.58-3.59L8 6l-6 6 6 6 1.41-1.41L5.83 13H21V7z" />
            </symbol>

            <symbol viewBox="0 0 24 24" id="expand">
                <path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z" />
            </symbol>

        </defs>
    </svg>


    <div id="swagger-ui">
        <div data-reactroot="" class="swagger-ui">
            <div>
                <div class="information-container wrapper">
                    <section class="block col-12">
                        <div class="info">
                            <hgroup class="main">
                                <h2 class="title">httpbin.org
                                    <small>
                                        <pre class="version">0.9.2</pre>
                                    </small>
                                </h2>
                                <pre class="base-url">[ Base URL: httpbin.org/ ]</pre>
                            </hgroup>
                            <div class="description">
                                <div class="markdown">
                                    <p>A simple HTTP Request &amp; Response Service.
                                        <br>
                                        <br>
                                        <b>Run locally: </b>
                                        <code>$ docker run -p 80:80 kennethreitz/httpbin</code>
                                    </p>
                                </div>
                            </div>
                            <div>
                                <div>
                                    <a href="https://kennethreitz.org" target="_blank">the developer - Website</a>
                                </div>
                                <a href="mailto:me@kennethreitz.org">Send email to the developer</a>
                            </div>
                        </div>
                        <!-- ADDS THE LOADER SPINNER -->
                        <div class="loading-container">
                            <div class="loading"></div>
                        </div>

                    </section>
                </div>
            </div>
        </div>
    </div>


    <div class='swagger-ui'>
        <div class="wrapper">
            <section class="clear">
                <span style="float: right;">
                    [Powered by
                    <a target="_blank" href="https://github.com/rochacbruno/flasgger">Flasgger</a>]
                    <br>
                </span>
            </section>
        </div>
    </div>



    <script src="/flasgger_static/swagger-ui-bundle.js"> </script>
    <script src="/flasgger_static/swagger-ui-standalone-preset.js"> </script>
    <script src='/flasgger_static/lib/jquery.min.js' type='text/javascript'></script>
    <script>

        window.onload = function () {


            fetch("/spec.json")
                .then(function (response) {
                    response.json()
                        .then(function (json) {
                            var current_protocol = window.location.protocol.slice(0, -1);
                            if (json.schemes[0] != current_protocol) {
                                // Switches scheme to the current in use
                                var other_protocol = json.schemes[0];
                                json.schemes[0] = current_protocol;
                                json.schemes[1] = other_protocol;

                            }
                            json.host = window.location.host;  // sets the current host

                            const ui = SwaggerUIBundle({
                                spec: json,
                                validatorUrl: null,
                                dom_id: '#swagger-ui',
                                deepLinking: true,
                                jsonEditor: true,
                                docExpansion: "none",
                                apisSorter: "alpha",
                                //operationsSorter: "alpha",
                                presets: [
                                    SwaggerUIBundle.presets.apis,
                                    // yay ES6 modules ↘
                                    Array.isArray(SwaggerUIStandalonePreset) ? SwaggerUIStandalonePreset : SwaggerUIStandalonePreset.default
                                ],
                                plugins: [
                                    SwaggerUIBundle.plugins.DownloadUrl
                                ],

            // layout: "StandaloneLayout"  // uncomment to enable the green top header
        })

        window.ui = ui

        // uncomment to rename the top brand if layout is enabled
        // $(".topbar-wrapper .link span").replaceWith("<span>httpbin</span>");
        })
    })
}
    </script>  <div class='swagger-ui'>
    <div class="wrapper">
        <section class="block col-12 block-desktop col-12-desktop">
            <div>

                <h2>Other Utilities</h2>

                <ul>
                    <li>
                        <a href="/forms/post">HTML form</a> that posts to /post /forms/post</li>
                </ul>

                <br />
                <br />
            </div>
        </section>
    </div>
</div>
</body>

</html>

- https://www.altexsoft.com/blog/rest-api-design/

## **HTTP verbs**
- There are 5 basic verb commands when making a HTTP request:

>- GET: make a read only request to view either a single or list of multiple resources
- POST: create a new resource based on the payload given in the body of the request
- DELETE: destroy the given resource based on the id provided
- PUT: update the entire fields of the resource based on the given body of the request or create a new one if not already exist
- PATCH: update only the fields of the resource if it exists

## <font color='orange'>**1. Python Request GET**
- GET는 HTTP Method의 하나로 페이지에 대한 정보를 요구하는 Method
- Path & Query 호ㅓㄱ인하고 POST, PUT, DELETE 메소드에 따라 다른 요청을 하는 것을 실습
- Endpoint란 API가 서버에서 자원(resource)에 접근할 수 있도록 하는 URL(돈 찾으러 은행가면 은행이 endpoint이고 창구은행원이 API)

In [ ]:
url = 'https://httpbin.org/get'  # endpoint  path

In [ ]:
# header & body
r = requests.get(url)
print(r.text)

{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.3",
    "X-Amzn-Trace-Id": "Root=1-6722a83d-4c3adc12370af8bf0e2a09c7"
  },
  "origin": "34.48.44.214",
  "url": "https://httpbin.org/get"
}

GET 요청에서 본문이 존재하지 않는 것은 자연스러운 상황입니다. 만약 본문을 포함한 요청을 하고 싶다면, POST 또는 PUT 같은 메소드를 사용하고 데이터를 요청 본문에 포함하여 전송하면 됩니다.

In [ ]:
r.headers

{'Date': 'Wed, 30 Oct 2024 21:42:21 GMT', 'Content-Type': 'application/json', 'Content-Length': '306', 'Connection': 'keep-alive', 'Server': 'gunicorn/19.9.0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true'}

In [ ]:
r.content

b'{\n  "args": {}, \n  "headers": {\n    "Accept": "*/*", \n    "Accept-Encoding": "gzip, deflate", \n    "Host": "httpbin.org", \n    "User-Agent": "python-requests/2.32.3", \n    "X-Amzn-Trace-Id": "Root=1-6722a83d-4c3adc12370af8bf0e2a09c7"\n  }, \n  "origin": "34.48.44.214", \n  "url": "https://httpbin.org/get"\n}\n'

In [ ]:
requests.get(url).text

'{\n  "args": {}, \n  "headers": {\n    "Accept": "*/*", \n    "Accept-Encoding": "gzip, deflate", \n    "Host": "httpbin.org", \n    "User-Agent": "python-requests/2.32.3", \n    "X-Amzn-Trace-Id": "Root=1-6722a979-37dbcbd879f0e8187ecda44d"\n  }, \n  "origin": "34.48.44.214", \n  "url": "https://httpbin.org/get"\n}\n'

In [ ]:
print(requests.get(url).text)

{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.3",
    "X-Amzn-Trace-Id": "Root=1-6722a986-5a1b3d1f5ef6fcac38f463ab"
  },
  "origin": "34.48.44.214",
  "url": "https://httpbin.org/get"
}

In [ ]:
print(type(requests.get(url).text))

<class 'str'>

In [ ]:
import json
json.loads(requests.get(url).text)

{'args': {},
 'headers': {'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate',
  'Host': 'httpbin.org',
  'User-Agent': 'python-requests/2.32.3',
  'X-Amzn-Trace-Id': 'Root=1-6722a996-262491ae26744a35706823bc'},
 'origin': '34.48.44.214',
 'url': 'https://httpbin.org/get'}

In [ ]:
type(json.loads(requests.get(url).text))

dict

In [ ]:
json.loads(requests.get(url).text)['headers']

{'Accept': '*/*',
 'Accept-Encoding': 'gzip, deflate',
 'Host': 'httpbin.org',
 'User-Agent': 'python-requests/2.32.3',
 'X-Amzn-Trace-Id': 'Root=1-6722a99a-43ef7d0d3cc3d41045cda6d4'}

>> ##### **URL에 GET 요청을 보내고, 해당 요청에 URL 쿼리 매개변수 'names'에 'sangoo' 값을 포함하여 보내는 것을 의미**
- https://api.example.com/data?names=sangoo (서버에 따라 다르지만 굳이 sanggoo가 없어도 된다)

In [ ]:
http_get_request = requests.get(url, params={'names': 'ancestor9'})
print(http_get_request.text)

{
  "args": {
    "names": "ancestor9"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.3",
    "X-Amzn-Trace-Id": "Root=1-6722a9de-620e7d8206e619653d7b18e2"
  },
  "origin": "34.48.44.214",
  "url": "https://httpbin.org/get?names=ancestor9"
}

In [ ]:
http_get_request = requests.get(url, params={'names': 'ancestor9', 'address': 'moon'})
print(http_get_request.text)

{
  "args": {
    "address": "moon",
    "names": "ancestor9"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.3",
    "X-Amzn-Trace-Id": "Root=1-6722a9f0-2490562d1316b55f155debea"
  },
  "origin": "34.48.44.214",
  "url": "https://httpbin.org/get?names=ancestor9&address=moon"
}

In [ ]:
print(http_get_request.status_code)

200

In [ ]:
http_get_request.json()

{'args': {'address': 'moon', 'names': 'ancestor9'},
 'headers': {'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate',
  'Host': 'httpbin.org',
  'User-Agent': 'python-requests/2.32.3',
  'X-Amzn-Trace-Id': 'Root=1-6722a9f0-2490562d1316b55f155debea'},
 'origin': '34.48.44.214',
 'url': 'https://httpbin.org/get?names=ancestor9&address=moon'}

In [ ]:
http_get_request.json().keys()

dict_keys(['args', 'headers', 'origin', 'url'])

In [ ]:
for key in http_get_request.json().keys():
    print(http_get_request.json()[key])

{'address': 'moon', 'names': 'ancestor9'}
{'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.32.3', 'X-Amzn-Trace-Id': 'Root=1-6722a9f0-2490562d1316b55f155debea'}
34.48.44.214
https://httpbin.org/get?names=ancestor9&address=moon

## <font color='orange'>**2. Python Request POST**
- POST는 HTTP Method의 하나로 form형태로 정보를 보내는 Method

In [ ]:
url = 'https://httpbin.org/post'
http_post_request = requests.post(url, data={'key': 'value'})
print(http_post_request.text)
print(http_post_request.status_code)

{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "key": "value"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "9",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.3",
    "X-Amzn-Trace-Id": "Root=1-6722ab1a-5d72f0f61960764c162e70f6"
  },
  "json": null,
  "origin": "34.48.44.214",
  "url": "https://httpbin.org/post"
}

200

In [ ]:
# 쿼리 문자열 인수 추가
params = {
    'name': 'example',
    'location': 'moon'
}

# POST 요청의 본문 데이터
data = {
    'key': 'value',
    'message': 'Hello, World!'
}

# POST 요청 보내기
http_post_request = requests.post(url, params=params, data=data)

# 응답 출력
print(http_post_request.text)

{
  "args": {
    "location": "moon",
    "name": "example"
  },
  "data": "",
  "files": {},
  "form": {
    "key": "value",
    "message": "Hello, World!"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "35",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.3",
    "X-Amzn-Trace-Id": "Root=1-6722ab53-150eefc277a4b2f635ae669a"
  },
  "json": null,
  "origin": "34.48.44.214",
  "url": "https://httpbin.org/post?name=example&location=moon"
}

In [ ]:
data = {'name': 'cho sanggoo',
        'age' : '57'}

http_post_request = requests.post(url, json=data)
print(http_post_request.text)
print(http_post_request.status_code)

{
  "args": {},
  "data": "{\"name\": \"cho sanggoo\", \"age\": \"57\"}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "36",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.32.3",
    "X-Amzn-Trace-Id": "Root=1-6722ab69-5658ead81ec8e0672a99ceca"
  },
  "json": {
    "age": "57",
    "name": "cho sanggoo"
  },
  "origin": "34.48.44.214",
  "url": "https://httpbin.org/post"
}

200

In [ ]:
r = requests.put('https://httpbin.org/put', data={'key': 'value'})
print(r)
r = requests.delete('https://httpbin.org/delete')
print(r)

<Response [200]>
<Response [200]>

## <font color='orange'> **Sample 예제**

In [ ]:
url = 'http://example.com/'  # Include the scheme (http or https)
http_get_request = requests.get(url)

In [ ]:
print(http_get_request)

<Response [200]>

In [ ]:
print(http_get_request.text)

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>

In [ ]:
url ='http://openapi.seoul.go.kr:8088/6d4d776b466c656533356a4b4b5872/json/RealtimeCityAir/1/99'

In [ ]:
res = requests.get(url)
res

In [ ]:
print(res.text)

{"RealtimeCityAir":{"list_total_count":25,"RESULT":{"CODE":"INFO-000","MESSAGE":"정상 처리되었습니다"},"row":[{"MSRDT":"202410310600","MSRRGN_NM":"도심권","MSRSTE_NM":"중구","PM10":26.0,"PM25":18.0,"O3":0.01,"NO2":0.021,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":61.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"도심권","MSRSTE_NM":"종로구","PM10":28.0,"PM25":20.0,"O3":0.011,"NO2":0.03,"CO":0.5,"SO2":0.004,"IDEX_NM":"보통","IDEX_MVL":69.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"도심권","MSRSTE_NM":"용산구","PM10":32.0,"PM25":19.0,"O3":0.005,"NO2":0.034,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":64.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서북권","MSRSTE_NM":"은평구","PM10":19.0,"PM25":13.0,"O3":0.011,"NO2":0.017,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":51.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서북권","MSRSTE_NM":"서대문구","PM10":26.0,"PM25":17.0,"O3":0.018,"NO2":0.025,"CO":0.6,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":56.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서북권","MSRSTE_NM":"마포구","PM10":29.0,"PM25":18.0,"O3":0.018,"NO2":0.024,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":61.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"광진구","PM10":25.0,"PM25":16.0,"O3":0.012,"NO2":0.025,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":56.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"성동구","PM10":28.0,"PM25":18.0,"O3":0.006,"NO2":0.031,"CO":0.4,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":61.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"중랑구","PM10":26.0,"PM25":17.0,"O3":0.015,"NO2":0.019,"CO":0.4,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":64.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"동대문구","PM10":31.0,"PM25":20.0,"O3":0.009,"NO2":0.03,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":66.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"성북구","PM10":27.0,"PM25":20.0,"O3":0.002,"NO2":0.033,"CO":0.7,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":61.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"도봉구","PM10":28.0,"PM25":17.0,"O3":0.006,"NO2":0.025,"CO":0.6,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":54.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"강북구","PM10":22.0,"PM25":15.0,"O3":0.019,"NO2":0.013,"CO":0.5,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":54.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동북권","MSRSTE_NM":"노원구","PM10":29.0,"PM25":19.0,"O3":0.007,"NO2":0.026,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":64.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서남권","MSRSTE_NM":"강서구","PM10":33.0,"PM25":20.0,"O3":0.002,"NO2":0.028,"CO":0.6,"SO2":0.004,"IDEX_NM":"보통","IDEX_MVL":64.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서남권","MSRSTE_NM":"구로구","PM10":34.0,"PM25":24.0,"O3":0.004,"NO2":0.028,"CO":0.5,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":74.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서남권","MSRSTE_NM":"영등포구","PM10":29.0,"PM25":19.0,"O3":0.007,"NO2":0.036,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":61.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서남권","MSRSTE_NM":"동작구","PM10":29.0,"PM25":19.0,"O3":0.003,"NO2":0.033,"CO":0.6,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":64.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서남권","MSRSTE_NM":"관악구","PM10":33.0,"PM25":20.0,"O3":0.006,"NO2":0.037,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":66.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서남권","MSRSTE_NM":"금천구","PM10":25.0,"PM25":20.0,"O3":0.007,"NO2":0.026,"CO":0.5,"SO2":0.003,"IDEX_NM":"보통","IDEX_MVL":61.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"서남권","MSRSTE_NM":"양천구","PM10":34.0,"PM25":21.0,"O3":0.002,"NO2":0.034,"CO":0.6,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":66.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동남권","MSRSTE_NM":"강남구","PM10":26.0,"PM25":17.0,"O3":0.014,"NO2":0.023,"CO":0.4,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":61.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동남권","MSRSTE_NM":"서초구","PM10":41.0,"PM25":26.0,"O3":0.005,"NO2":0.034,"CO":0.5,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":74.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동남권","MSRSTE_NM":"송파구","PM10":32.0,"PM25":20.0,"O3":0.002,"NO2":0.033,"CO":0.6,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":64.0,"ARPLT_MAIN":"PM-2.5"},{"MSRDT":"202410310600","MSRRGN_NM":"동남권","MSRSTE_NM":"강동구","PM10":28.0,"PM25":18.0,"O3":0.005,"NO2":0.027,"CO":0.5,"SO2":0.002,"IDEX_NM":"보통","IDEX_MVL":66.0,"ARPLT_MAIN":"PM-2.5"}]}}

In [ ]:
type(res.text)

str

In [ ]:
print(res.json())

{'RealtimeCityAir': {'list_total_count': 25, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}, 'row': [{'MSRDT': '202410310600', 'MSRRGN_NM': '도심권', 'MSRSTE_NM': '중구', 'PM10': 26.0, 'PM25': 18.0, 'O3': 0.01, 'NO2': 0.021, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 61.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '도심권', 'MSRSTE_NM': '종로구', 'PM10': 28.0, 'PM25': 20.0, 'O3': 0.011, 'NO2': 0.03, 'CO': 0.5, 'SO2': 0.004, 'IDEX_NM': '보통', 'IDEX_MVL': 69.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '도심권', 'MSRSTE_NM': '용산구', 'PM10': 32.0, 'PM25': 19.0, 'O3': 0.005, 'NO2': 0.034, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 64.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서북권', 'MSRSTE_NM': '은평구', 'PM10': 19.0, 'PM25': 13.0, 'O3': 0.011, 'NO2': 0.017, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 51.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서북권', 'MSRSTE_NM': '서대문구', 'PM10': 26.0, 'PM25': 17.0, 'O3': 0.018, 'NO2': 0.025, 'CO': 0.6, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 56.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서북권', 'MSRSTE_NM': '마포구', 'PM10': 29.0, 'PM25': 18.0, 'O3': 0.018, 'NO2': 0.024, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 61.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '광진구', 'PM10': 25.0, 'PM25': 16.0, 'O3': 0.012, 'NO2': 0.025, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 56.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '성동구', 'PM10': 28.0, 'PM25': 18.0, 'O3': 0.006, 'NO2': 0.031, 'CO': 0.4, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 61.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '중랑구', 'PM10': 26.0, 'PM25': 17.0, 'O3': 0.015, 'NO2': 0.019, 'CO': 0.4, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 64.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '동대문구', 'PM10': 31.0, 'PM25': 20.0, 'O3': 0.009, 'NO2': 0.03, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 66.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '성북구', 'PM10': 27.0, 'PM25': 20.0, 'O3': 0.002, 'NO2': 0.033, 'CO': 0.7, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 61.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '도봉구', 'PM10': 28.0, 'PM25': 17.0, 'O3': 0.006, 'NO2': 0.025, 'CO': 0.6, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 54.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '강북구', 'PM10': 22.0, 'PM25': 15.0, 'O3': 0.019, 'NO2': 0.013, 'CO': 0.5, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 54.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동북권', 'MSRSTE_NM': '노원구', 'PM10': 29.0, 'PM25': 19.0, 'O3': 0.007, 'NO2': 0.026, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 64.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서남권', 'MSRSTE_NM': '강서구', 'PM10': 33.0, 'PM25': 20.0, 'O3': 0.002, 'NO2': 0.028, 'CO': 0.6, 'SO2': 0.004, 'IDEX_NM': '보통', 'IDEX_MVL': 64.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서남권', 'MSRSTE_NM': '구로구', 'PM10': 34.0, 'PM25': 24.0, 'O3': 0.004, 'NO2': 0.028, 'CO': 0.5, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 74.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서남권', 'MSRSTE_NM': '영등포구', 'PM10': 29.0, 'PM25': 19.0, 'O3': 0.007, 'NO2': 0.036, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 61.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서남권', 'MSRSTE_NM': '동작구', 'PM10': 29.0, 'PM25': 19.0, 'O3': 0.003, 'NO2': 0.033, 'CO': 0.6, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 64.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서남권', 'MSRSTE_NM': '관악구', 'PM10': 33.0, 'PM25': 20.0, 'O3': 0.006, 'NO2': 0.037, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 66.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서남권', 'MSRSTE_NM': '금천구', 'PM10': 25.0, 'PM25': 20.0, 'O3': 0.007, 'NO2': 0.026, 'CO': 0.5, 'SO2': 0.003, 'IDEX_NM': '보통', 'IDEX_MVL': 61.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '서남권', 'MSRSTE_NM': '양천구', 'PM10': 34.0, 'PM25': 21.0, 'O3': 0.002, 'NO2': 0.034, 'CO': 0.6, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 66.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동남권', 'MSRSTE_NM': '강남구', 'PM10': 26.0, 'PM25': 17.0, 'O3': 0.014, 'NO2': 0.023, 'CO': 0.4, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 61.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동남권', 'MSRSTE_NM': '서초구', 'PM10': 41.0, 'PM25': 26.0, 'O3': 0.005, 'NO2': 0.034, 'CO': 0.5, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 74.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동남권', 'MSRSTE_NM': '송파구', 'PM10': 32.0, 'PM25': 20.0, 'O3': 0.002, 'NO2': 0.033, 'CO': 0.6, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 64.0, 'ARPLT_MAIN': 'PM-2.5'}, {'MSRDT': '202410310600', 'MSRRGN_NM': '동남권', 'MSRSTE_NM': '강동구', 'PM10': 28.0, 'PM25': 18.0, 'O3': 0.005, 'NO2': 0.027, 'CO': 0.5, 'SO2': 0.002, 'IDEX_NM': '보통', 'IDEX_MVL': 66.0, 'ARPLT_MAIN': 'PM-2.5'}]}}

In [ ]:
type(res.json())

dict

##@ 사전형은 데이터로 조작 가능 - callable
- type(res.text())

In [ ]:
type(res.text())

TypeError: 'str' object is not callable

In [ ]:
resj = res.json()

In [ ]:
import pandas as pd
pd.DataFrame(resj)

                                                    RealtimeCityAir
list_total_count                                                 25
RESULT                {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}
row               [{'MSRDT': '202410310600', 'MSRRGN_NM': '도심권',...

In [ ]:
resj['RealtimeCityAir']

{'list_total_count': 25,
 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
 'row': [{'MSRDT': '202410310600',
   'MSRRGN_NM': '도심권',
   'MSRSTE_NM': '중구',
   'PM10': 26.0,
   'PM25': 18.0,
   'O3': 0.01,
   'NO2': 0.021,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 61.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '도심권',
   'MSRSTE_NM': '종로구',
   'PM10': 28.0,
   'PM25': 20.0,
   'O3': 0.011,
   'NO2': 0.03,
   'CO': 0.5,
   'SO2': 0.004,
   'IDEX_NM': '보통',
   'IDEX_MVL': 69.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '도심권',
   'MSRSTE_NM': '용산구',
   'PM10': 32.0,
   'PM25': 19.0,
   'O3': 0.005,
   'NO2': 0.034,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 64.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서북권',
   'MSRSTE_NM': '은평구',
   'PM10': 19.0,
   'PM25': 13.0,
   'O3': 0.011,
   'NO2': 0.017,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 51.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서북권',
   'MSRSTE_NM': '서대문구',
   'PM10': 26.0,
   'PM25': 17.0,
   'O3': 0.018,
   'NO2': 0.025,
   'CO': 0.6,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 56.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서북권',
   'MSRSTE_NM': '마포구',
   'PM10': 29.0,
   'PM25': 18.0,
   'O3': 0.018,
   'NO2': 0.024,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 61.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '광진구',
   'PM10': 25.0,
   'PM25': 16.0,
   'O3': 0.012,
   'NO2': 0.025,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 56.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '성동구',
   'PM10': 28.0,
   'PM25': 18.0,
   'O3': 0.006,
   'NO2': 0.031,
   'CO': 0.4,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 61.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '중랑구',
   'PM10': 26.0,
   'PM25': 17.0,
   'O3': 0.015,
   'NO2': 0.019,
   'CO': 0.4,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 64.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '동대문구',
   'PM10': 31.0,
   'PM25': 20.0,
   'O3': 0.009,
   'NO2': 0.03,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 66.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '성북구',
   'PM10': 27.0,
   'PM25': 20.0,
   'O3': 0.002,
   'NO2': 0.033,
   'CO': 0.7,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 61.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '도봉구',
   'PM10': 28.0,
   'PM25': 17.0,
   'O3': 0.006,
   'NO2': 0.025,
   'CO': 0.6,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 54.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '강북구',
   'PM10': 22.0,
   'PM25': 15.0,
   'O3': 0.019,
   'NO2': 0.013,
   'CO': 0.5,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 54.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동북권',
   'MSRSTE_NM': '노원구',
   'PM10': 29.0,
   'PM25': 19.0,
   'O3': 0.007,
   'NO2': 0.026,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 64.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서남권',
   'MSRSTE_NM': '강서구',
   'PM10': 33.0,
   'PM25': 20.0,
   'O3': 0.002,
   'NO2': 0.028,
   'CO': 0.6,
   'SO2': 0.004,
   'IDEX_NM': '보통',
   'IDEX_MVL': 64.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서남권',
   'MSRSTE_NM': '구로구',
   'PM10': 34.0,
   'PM25': 24.0,
   'O3': 0.004,
   'NO2': 0.028,
   'CO': 0.5,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 74.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서남권',
   'MSRSTE_NM': '영등포구',
   'PM10': 29.0,
   'PM25': 19.0,
   'O3': 0.007,
   'NO2': 0.036,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 61.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서남권',
   'MSRSTE_NM': '동작구',
   'PM10': 29.0,
   'PM25': 19.0,
   'O3': 0.003,
   'NO2': 0.033,
   'CO': 0.6,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 64.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서남권',
   'MSRSTE_NM': '관악구',
   'PM10': 33.0,
   'PM25': 20.0,
   'O3': 0.006,
   'NO2': 0.037,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 66.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서남권',
   'MSRSTE_NM': '금천구',
   'PM10': 25.0,
   'PM25': 20.0,
   'O3': 0.007,
   'NO2': 0.026,
   'CO': 0.5,
   'SO2': 0.003,
   'IDEX_NM': '보통',
   'IDEX_MVL': 61.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '서남권',
   'MSRSTE_NM': '양천구',
   'PM10': 34.0,
   'PM25': 21.0,
   'O3': 0.002,
   'NO2': 0.034,
   'CO': 0.6,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 66.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동남권',
   'MSRSTE_NM': '강남구',
   'PM10': 26.0,
   'PM25': 17.0,
   'O3': 0.014,
   'NO2': 0.023,
   'CO': 0.4,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 61.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동남권',
   'MSRSTE_NM': '서초구',
   'PM10': 41.0,
   'PM25': 26.0,
   'O3': 0.005,
   'NO2': 0.034,
   'CO': 0.5,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 74.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동남권',
   'MSRSTE_NM': '송파구',
   'PM10': 32.0,
   'PM25': 20.0,
   'O3': 0.002,
   'NO2': 0.033,
   'CO': 0.6,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 64.0,
   'ARPLT_MAIN': 'PM-2.5'},
  {'MSRDT': '202410310600',
   'MSRRGN_NM': '동남권',
   'MSRSTE_NM': '강동구',
   'PM10': 28.0,
   'PM25': 18.0,
   'O3': 0.005,
   'NO2': 0.027,
   'CO': 0.5,
   'SO2': 0.002,
   'IDEX_NM': '보통',
   'IDEX_MVL': 66.0,
   'ARPLT_MAIN': 'PM-2.5'}]}

In [ ]:
resj['RealtimeCityAir']['row']

[{'MSRDT': '202410310600',
  'MSRRGN_NM': '도심권',
  'MSRSTE_NM': '중구',
  'PM10': 26.0,
  'PM25': 18.0,
  'O3': 0.01,
  'NO2': 0.021,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 61.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '도심권',
  'MSRSTE_NM': '종로구',
  'PM10': 28.0,
  'PM25': 20.0,
  'O3': 0.011,
  'NO2': 0.03,
  'CO': 0.5,
  'SO2': 0.004,
  'IDEX_NM': '보통',
  'IDEX_MVL': 69.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '도심권',
  'MSRSTE_NM': '용산구',
  'PM10': 32.0,
  'PM25': 19.0,
  'O3': 0.005,
  'NO2': 0.034,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 64.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서북권',
  'MSRSTE_NM': '은평구',
  'PM10': 19.0,
  'PM25': 13.0,
  'O3': 0.011,
  'NO2': 0.017,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 51.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서북권',
  'MSRSTE_NM': '서대문구',
  'PM10': 26.0,
  'PM25': 17.0,
  'O3': 0.018,
  'NO2': 0.025,
  'CO': 0.6,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 56.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서북권',
  'MSRSTE_NM': '마포구',
  'PM10': 29.0,
  'PM25': 18.0,
  'O3': 0.018,
  'NO2': 0.024,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 61.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '광진구',
  'PM10': 25.0,
  'PM25': 16.0,
  'O3': 0.012,
  'NO2': 0.025,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 56.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '성동구',
  'PM10': 28.0,
  'PM25': 18.0,
  'O3': 0.006,
  'NO2': 0.031,
  'CO': 0.4,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 61.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '중랑구',
  'PM10': 26.0,
  'PM25': 17.0,
  'O3': 0.015,
  'NO2': 0.019,
  'CO': 0.4,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 64.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '동대문구',
  'PM10': 31.0,
  'PM25': 20.0,
  'O3': 0.009,
  'NO2': 0.03,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 66.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '성북구',
  'PM10': 27.0,
  'PM25': 20.0,
  'O3': 0.002,
  'NO2': 0.033,
  'CO': 0.7,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 61.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '도봉구',
  'PM10': 28.0,
  'PM25': 17.0,
  'O3': 0.006,
  'NO2': 0.025,
  'CO': 0.6,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 54.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '강북구',
  'PM10': 22.0,
  'PM25': 15.0,
  'O3': 0.019,
  'NO2': 0.013,
  'CO': 0.5,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 54.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동북권',
  'MSRSTE_NM': '노원구',
  'PM10': 29.0,
  'PM25': 19.0,
  'O3': 0.007,
  'NO2': 0.026,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 64.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서남권',
  'MSRSTE_NM': '강서구',
  'PM10': 33.0,
  'PM25': 20.0,
  'O3': 0.002,
  'NO2': 0.028,
  'CO': 0.6,
  'SO2': 0.004,
  'IDEX_NM': '보통',
  'IDEX_MVL': 64.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서남권',
  'MSRSTE_NM': '구로구',
  'PM10': 34.0,
  'PM25': 24.0,
  'O3': 0.004,
  'NO2': 0.028,
  'CO': 0.5,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 74.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서남권',
  'MSRSTE_NM': '영등포구',
  'PM10': 29.0,
  'PM25': 19.0,
  'O3': 0.007,
  'NO2': 0.036,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 61.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서남권',
  'MSRSTE_NM': '동작구',
  'PM10': 29.0,
  'PM25': 19.0,
  'O3': 0.003,
  'NO2': 0.033,
  'CO': 0.6,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 64.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서남권',
  'MSRSTE_NM': '관악구',
  'PM10': 33.0,
  'PM25': 20.0,
  'O3': 0.006,
  'NO2': 0.037,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 66.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서남권',
  'MSRSTE_NM': '금천구',
  'PM10': 25.0,
  'PM25': 20.0,
  'O3': 0.007,
  'NO2': 0.026,
  'CO': 0.5,
  'SO2': 0.003,
  'IDEX_NM': '보통',
  'IDEX_MVL': 61.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '서남권',
  'MSRSTE_NM': '양천구',
  'PM10': 34.0,
  'PM25': 21.0,
  'O3': 0.002,
  'NO2': 0.034,
  'CO': 0.6,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 66.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동남권',
  'MSRSTE_NM': '강남구',
  'PM10': 26.0,
  'PM25': 17.0,
  'O3': 0.014,
  'NO2': 0.023,
  'CO': 0.4,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 61.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동남권',
  'MSRSTE_NM': '서초구',
  'PM10': 41.0,
  'PM25': 26.0,
  'O3': 0.005,
  'NO2': 0.034,
  'CO': 0.5,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 74.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동남권',
  'MSRSTE_NM': '송파구',
  'PM10': 32.0,
  'PM25': 20.0,
  'O3': 0.002,
  'NO2': 0.033,
  'CO': 0.6,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 64.0,
  'ARPLT_MAIN': 'PM-2.5'},
 {'MSRDT': '202410310600',
  'MSRRGN_NM': '동남권',
  'MSRSTE_NM': '강동구',
  'PM10': 28.0,
  'PM25': 18.0,
  'O3': 0.005,
  'NO2': 0.027,
  'CO': 0.5,
  'SO2': 0.002,
  'IDEX_NM': '보통',
  'IDEX_MVL': 66.0,
  'ARPLT_MAIN': 'PM-2.5'}]

In [ ]:
resj['RealtimeCityAir']['row'][0]

{'MSRDT': '202410310600',
 'MSRRGN_NM': '도심권',
 'MSRSTE_NM': '중구',
 'PM10': 26.0,
 'PM25': 18.0,
 'O3': 0.01,
 'NO2': 0.021,
 'CO': 0.5,
 'SO2': 0.003,
 'IDEX_NM': '보통',
 'IDEX_MVL': 61.0,
 'ARPLT_MAIN': 'PM-2.5'}

In [ ]:
resj['RealtimeCityAir']['row'][0]['NO2']

0.021

### 딕셔너리 callable - 계층구조로 drill down이 가능
### pd.json.normalize() 함수는 계층화된 구조의 데이터를 펴준다

In [ ]:
pd.json_normalize(resj['RealtimeCityAir']['row'])

,MSRDT,MSRRGN_NM,MSRSTE_NM,PM10,PM25,O3,NO2,CO,SO2,IDEX_NM,IDEX_MVL,ARPLT_MAIN
0,202410310600,도심권,중구,26.0,18.0,0.010,0.021,0.5,0.003,보통,61.0,PM-2.5
1,202410310600,도심권,종로구,28.0,20.0,0.011,0.030,0.5,0.004,보통,69.0,PM-2.5
2,202410310600,도심권,용산구,32.0,19.0,0.005,0.034,0.5,0.003,보통,64.0,PM-2.5
3,202410310600,서북권,은평구,19.0,13.0,0.011,0.017,0.5,0.003,보통,51.0,PM-2.5
4,202410310600,서북권,서대문구,26.0,17.0,0.018,0.025,0.6,0.003,보통,56.0,PM-2.5
5,202410310600,서북권,마포구,29.0,18.0,0.018,0.024,0.5,0.003,보통,61.0,PM-2.5
6,202410310600,동북권,광진구,25.0,16.0,0.012,0.025,0.5,0.003,보통,56.0,PM-2.5
7,202410310600,동북권,성동구,28.0,18.0,0.006,0.031,0.4,0.003,보통,61.0,PM-2.5
8,202410310600,동북권,중랑구,26.0,17.0,0.015,0.019,0.4,0.002,보통,64.0,PM-2.5
9,202410310600,동북권,동대문구,31.0,20.0,0.009,0.030,0.5,0.003,보통,66.0,PM-2.5
10,202410310600,동북권,성북구,27.0,20.0,0.002,0.033,0.7,0.003,보통,61.0,PM-2.5
11,202410310600,동북권,도봉구,28.0,17.0,0.006,0.025,0.6,0.003,보통,54.0,PM-2.5
12,202410310600,동북권,강북구,22.0,15.0,0.019,0.013,0.5,0.002,보통,54.0,PM-2.5
13,202410310600,동북권,노원구,29.0,19.0,0.007,0.026,0.5,0.003,보통,64.0,PM-2.5
14,202410310600,서남권,강서구,33.0,20.0,0.002,0.028,0.6,0.004,보통,64.0,PM-2.5
15,202410310600,서남권,구로구,34.0,24.0,0.004,0.028,0.5,0.002,보통,74.0,PM-2.5
16,202410310600,서남권,영등포구,29.0,19.0,0.007,0.036,0.5,0.003,보통,61.0,PM-2.5
17,202410310600,서남권,동작구,29.0,19.0,0.003,0.033,0.6,0.003,보통,64.0,PM-2.5
18,202410310600,서남권,관악구,33.0,20.0,0.006,0.037,0.5,0.003,보통,66.0,PM-2.5
19,202410310600,서남권,금천구,25.0,20.0,0.007,0.026,0.5,0.003,보통,61.0,PM-2.5
20,202410310600,서남권,양천구,34.0,21.0,0.002,0.034,0.6,0.002,보통,66.0,PM-2.5
21,202410310600,동남권,강남구,26.0,17.0,0.014,0.023,0.4,0.002,보통,61.0,PM-2.5
22,202410310600,동남권,서초구,41.0,26.0,0.005,0.034,0.5,0.002,보통,74.0,PM-2.5
23,202410310600,동남권,송파구,32.0,20.0,0.002,0.033,0.6,0.002,보통,64.0,PM-2.5
24,202410310600,동남권,강동구,28.0,18.0,0.005,0.027,0.5,0.002,보통,66.0,PM-2.5

### 과제. HTTP server를 사용하여 Client와 Server 코드를 만들어라
- vs code에서 로컬환경에서 py 파일로 2개 코드, sever.py와 clietn.py를 만들어 통신하라